module.exports = {
  'toID': {
    'Bills': 0,
    'Dolphins': 1,
    'Patriots': 2,
    'Jets': 3,
    'Ravens': 4,
    'Bengals': 5,
    'Browns': 6,
    'Steelers': 7,
    'Texans': 8,
    'Colts': 9,
    'Jaguars': 10,
    'Titans': 11,
    'Broncos': 12,
    'Chiefs': 13,
    'Raiders': 14,
    'Chargers': 15,
    'Cowboys': 16,
    'Giants': 17,
    'Eagles': 18,
    'Redskins': 19,
    'Bears': 20,
    'Lions': 21,
    'Packers': 22,
    'Vikings': 23,
    'Falcons': 24,
    'Panthers': 25,
    'Saints': 26,
    'Buccaneers': 27,
    'Cardinals': 28,
    'Rams': 29,
    '49ers': 30,
    'Seahawks': 31,
  },
  'toName': [
    'Bills',
    'Dolphins',
    'Patriots',
    'Jets',
    'Ravens',
    'Bengals',
    'Browns',
    'Steelers',
    'Texans',
    'Colts',
    'Jaguars',
    'Titans',
    'Broncos',
    'Chiefs',
    'Raiders',
    'Chargers',
    'Cowboys',
    'Giants',
    'Eagles',
    'Redskins',
    'Bears',
    'Lions',
    'Packers',
    'Vikings',
    'Falcons',
    'Panthers',
    'Saints',
    'Buccaneers',
    'Cardinals',
    'Rams',
    '49ers',
    'Seahawks'
  ]
};
